stages:
  - build
  - deploy

create_zip:
  stage: build
  script:
    - echo "Creating zip file"
    - zip -r latest.zip contents metadata.json
  artifacts:
    paths:
      - latest.zip
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG'

release:
  stage: deploy
  script:
    - echo "Releasing"
    - >
      curl --header "Project-ID: $CI_PROJECT_ID" --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" 
      --data "name=Release $CI_COMMIT_TAG" --data "tag_name=$CI_COMMIT_TAG" 
      --data "description=Release of $CI_COMMIT_TAG" 
      "https://www.opencode.net/api/v4/projects/$CI_PROJECT_ID/releases"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG'
