image: debian:latest

stages:
  - build
  - deploy

create_zip:
  stage: build
  script:
    - echo "Creating zip file"
    #- apt-get update && apt-get install -y zip
    - zip -r latest.zip contents metadata.json
  artifacts:
    paths:
      - latest.zip
  only:
    - main

release:
  stage: deploy
  script:
    - echo "Releasing"
    - >
      curl --header "Project-ID: $CI_PROJECT_ID" --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" 
      --data "name=Release $CI_COMMIT_TAG" --data "tag_name=$CI_COMMIT_TAG" 
      --data "description=Release of $CI_COMMIT_TAG" 
      "https://www.opencode.net/api/v4/projects/$CI_PROJECT_ID/releases"
  only:
    - main
